config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('catalog.urls', namespace='catalog')),
    path('materials/', include('materials.urls', namespace='materials')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, UserPasswordChange

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name="users/password_reset_email.html",
                                                      success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password_reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(max_length=255, unique=True)

    avatar = models.ImageField(upload_to='avatars', **NULLABLE, verbose_name='Аватар')
    phone = models.CharField(max_length=255, **NULLABLE, verbose_name='Телефон')
    country = models.CharField(max_length=255, **NULLABLE, verbose_name='Страна')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, PasswordResetForm
from django import forms
from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

users/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, PasswordResetView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView

from users.forms import UserRegisterForm, UserProfileForm, UserPasswordChangeForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    extra_context = {'title': 'Профиль пользователя'}
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'

users/templates/users/error_verify.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Электронная почта не подтверждена</h4>
        <p>Ваш адрес электронной почты не подтвержден!</p>
        <p><a href="{% url 'users:register' %}">Перейти на форму регистрации</a></p>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content%}
<div class="col-12">
    <div class="row mt-2 justify-content-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Добавление пользователя
                    </h3>
                </div>
                <div class="card-body">
                    <h4 class="card-title">Вход</h4>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" value="Войти">
                        </div>
                        <a class="btn btn-link" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_change_done.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Пароль успешно изменен</h4>
    </div>


    <p><a href="{% url 'users:login' %}">Перейти на форму авторизации</a></p>

{% endblock %}

users/templates/users/password_change_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p ><button type="submit">Изменить пароль</button></p>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Пароль успешно изменен</h4>
    </div>


    <p><a href="{% url 'users:login' %}">Перейти на форму авторизации</a></p>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>New password</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary"> Save </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="alert alert-info" role="alert">
    <p>
      На ваш адрес электронной почты было отправлено письмо со ссылкой на восстановление пароля.
      Пожалуйста, проверьте свою электронную почту и нажмите на ссылку, чтобы восстановить или сменить пароль пользователя.<br />
      Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% blocktranslate %}You're receiving this email because you requested a password reset for your user account at
        {{ site_name }}.{% endblocktranslate %}

    {% translate "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}
    {% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

    {% translate "Thanks for using our site!" %}

    {% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
  <div class="row text-center">
    <div class="col-3">
      <div class="card mb-4 box-shadow">
        <div class="card-header">

          <h3>Восстановление пароля</h3>
          <p>Введите e-mail, вам будет отправлено письмо</p>


          <form method="post">
            {% csrf_token %}
            <input type="email" name="email" placeholder="Email" required>
            {% if error_message %}
            <p style="color: red;">{{ error_message }}</p>
            {% endif %}
            <button type="submit" class="btn btn-primary">Сбросить по email адресу</button>
          </form>

        </div>
      </div>
    </div>
  </div>


  {% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content%}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register_done.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Добро пожаловать!</h4>
        <p>Вы успешно зарегистрирваны на сайте! Для входа в систему необходимо авторизоваться по этой
            <a href="{% url 'users:login' %}">ссылке</a></p>
    </div>
{% endblock %}

users/templates/users/success_verify.html
{% extends "catalog/base.html" %}

{% block content %}
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден!</p>
    <p><a href="{% url 'users:login' %}">Перейти на форму авторизации</a></p>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}
{% block content%}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Профиль
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                    <a href="{% url 'users:password_change' %}" class="btn btn-danger w-50 mt-2">Сменить пароль</a>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}